-- 回滚：移除 018 添加的 tenant_id 列

DROP INDEX IF EXISTS idx_abilitydomains_tenant;
DROP INDEX IF EXISTS idx_abilitypoints_tenant;
DROP INDEX IF EXISTS idx_announcements_tenant;
DROP INDEX IF EXISTS idx_appmodules_tenant;
DROP INDEX IF EXISTS idx_appealrecords_tenant;
DROP INDEX IF EXISTS idx_authorizations_tenant;
DROP INDEX IF EXISTS idx_bannerconfigs_tenant;
DROP INDEX IF EXISTS idx_banners_tenant;
DROP INDEX IF EXISTS idx_careerpositions_tenant;
DROP INDEX IF EXISTS idx_certissuancerecords_tenant;
DROP INDEX IF EXISTS idx_certificationabilityitems_tenant;
DROP INDEX IF EXISTS idx_certificationabilitypoints_tenant;
DROP INDEX IF EXISTS idx_certificationrelatedtasks_tenant;
DROP INDEX IF EXISTS idx_certificationrules_tenant;
DROP INDEX IF EXISTS idx_courseknowledgebindings_tenant;
DROP INDEX IF EXISTS idx_courses_tenant;
DROP INDEX IF EXISTS idx_creditconversionrules_tenant;
DROP INDEX IF EXISTS idx_evaluationmethodcategories_tenant;
DROP INDEX IF EXISTS idx_evaluationmethods_tenant;
DROP INDEX IF EXISTS idx_examquestions_tenant;
DROP INDEX IF EXISTS idx_examresults_tenant;
DROP INDEX IF EXISTS idx_examusages_tenant;
DROP INDEX IF EXISTS idx_exams_tenant;
DROP INDEX IF EXISTS idx_graduationprojectarchives_tenant;
DROP INDEX IF EXISTS idx_graduationprojectevaluations_tenant;
DROP INDEX IF EXISTS idx_graduationprojecttopics_tenant;
DROP INDEX IF EXISTS idx_graduationqueryresults_tenant;
DROP INDEX IF EXISTS idx_hybridnodemodules_tenant;
DROP INDEX IF EXISTS idx_institutionexpertisetags_tenant;
DROP INDEX IF EXISTS idx_jobabilityresults_tenant;
DROP INDEX IF EXISTS idx_knowledgepoints_tenant;
DROP INDEX IF EXISTS idx_learnroads_tenant;
DROP INDEX IF EXISTS idx_lessonbehaviorrecords_tenant;
DROP INDEX IF EXISTS idx_microcerttemplates_tenant;
DROP INDEX IF EXISTS idx_nodehomeworks_tenant;
DROP INDEX IF EXISTS idx_nodequizquestions_tenant;
DROP INDEX IF EXISTS idx_nodequizzes_tenant;
DROP INDEX IF EXISTS idx_noderesources_tenant;
DROP INDEX IF EXISTS idx_orders_tenant;
DROP INDEX IF EXISTS idx_platformlinks_tenant;
DROP INDEX IF EXISTS idx_positionabilitybindings_tenant;
DROP INDEX IF EXISTS idx_positioncertificates_tenant;
DROP INDEX IF EXISTS idx_positionrecommendations_tenant;
DROP INDEX IF EXISTS idx_positionresponsibilities_tenant;
DROP INDEX IF EXISTS idx_questionbanks_tenant;
DROP INDEX IF EXISTS idx_questions_tenant;
DROP INDEX IF EXISTS idx_resourcetags_tenant;
DROP INDEX IF EXISTS idx_resources_tenant;
DROP INDEX IF EXISTS idx_scenariogrademappings_tenant;
DROP INDEX IF EXISTS idx_scenarioweightconfigs_tenant;
DROP INDEX IF EXISTS idx_scenearchives_tenant;
DROP INDEX IF EXISTS idx_sceneevaluationresults_tenant;
DROP INDEX IF EXISTS idx_studentabilityarchives_tenant;
DROP INDEX IF EXISTS idx_studentabilityportraits_tenant;
DROP INDEX IF EXISTS idx_systemcoursenodes_tenant;
DROP INDEX IF EXISTS idx_taskabilitybindings_tenant;
DROP INDEX IF EXISTS idx_taskdeliverables_tenant;
DROP INDEX IF EXISTS idx_taskevalpoints_tenant;
DROP INDEX IF EXISTS idx_taskevaluationconfigs_tenant;
DROP INDEX IF EXISTS idx_taskknowledgebindings_tenant;
DROP INDEX IF EXISTS idx_taskresourcebindings_tenant;
DROP INDEX IF EXISTS idx_taskresources_tenant;
DROP INDEX IF EXISTS idx_taskreviewsteps_tenant;
DROP INDEX IF EXISTS idx_withdrawals_tenant;
ALTER TABLE ability_domains DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE ability_points DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE announcements DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE app_modules DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE appeal_records DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE authorizations DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE banner_configs DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE banners DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE career_positions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE cert_issuance_records DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE certification_ability_items DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE certification_ability_points DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE certification_related_tasks DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE certification_rules DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE course_knowledge_bindings DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE courses DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE credit_conversion_rules DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE evaluation_method_categories DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE evaluation_methods DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE exam_questions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE exam_results DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE exam_usages DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE exams DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE graduation_project_archives DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE graduation_project_evaluations DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE graduation_project_topics DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE graduation_query_results DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE hybrid_node_modules DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE institution_expertise_tags DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE job_ability_results DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE knowledge_points DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE learn_roads DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE lesson_behavior_records DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE micro_cert_templates DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE node_homeworks DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE node_quiz_questions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE node_quizzes DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE node_resources DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE orders DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE platform_links DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE position_ability_bindings DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE position_certificates DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE position_recommendations DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE position_responsibilities DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE question_banks DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE questions DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE resource_tags DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE resources DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE scenario_grade_mappings DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE scenario_weight_configs DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE scene_archives DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE scene_evaluation_results DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE student_ability_archives DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE student_ability_portraits DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE system_course_nodes DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_ability_bindings DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_deliverables DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_eval_points DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_evaluation_configs DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_knowledge_bindings DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_resource_bindings DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_resources DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE task_review_steps DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE withdrawals DROP COLUMN IF EXISTS tenant_id;
