ALTER TABLE certification_grade_leaderboard ADD COLUMN major VARCHAR(128);
ALTER TABLE job_ability_results ADD COLUMN major VARCHAR(128);
ALTER TABLE exam_results ADD COLUMN major VARCHAR(128);
ALTER TABLE exam_usages ADD COLUMN major VARCHAR(128);
ALTER TABLE evaluation_batches ADD COLUMN major VARCHAR(128);
ALTER TABLE scene_batches ADD COLUMN major VARCHAR(128);
ALTER TABLE lesson_batches ADD COLUMN major VARCHAR(128);
ALTER TABLE courses ADD COLUMN major VARCHAR(128);
ALTER TABLE courses ADD COLUMN industry VARCHAR(128);
ALTER TABLE courses DROP CONSTRAINT fk_courses_industry;
ALTER TABLE courses DROP COLUMN industry_id;
ALTER TABLE position_recommendations ADD COLUMN major VARCHAR(128);
ALTER TABLE batches ADD COLUMN major VARCHAR(128);

ALTER TABLE certification_grade_leaderboard DROP CONSTRAINT fk_certification_grade_leaderboard_major;
ALTER TABLE job_ability_results DROP CONSTRAINT fk_job_ability_results_major;
ALTER TABLE exam_results DROP CONSTRAINT fk_exam_results_major;
ALTER TABLE exam_usages DROP CONSTRAINT fk_exam_usages_major;
ALTER TABLE evaluation_batches DROP CONSTRAINT fk_evaluation_batches_major;
ALTER TABLE scene_batches DROP CONSTRAINT fk_scene_batches_major;
ALTER TABLE lesson_batches DROP CONSTRAINT fk_lesson_batches_major;
ALTER TABLE courses DROP CONSTRAINT fk_courses_major;
ALTER TABLE position_recommendations DROP CONSTRAINT fk_position_recommendations_major;
ALTER TABLE batches DROP CONSTRAINT fk_batches_major;

ALTER TABLE certification_grade_leaderboard DROP COLUMN major_id;
ALTER TABLE job_ability_results DROP COLUMN major_id;
ALTER TABLE exam_results DROP COLUMN major_id;
ALTER TABLE exam_usages DROP COLUMN major_id;
ALTER TABLE evaluation_batches DROP COLUMN major_id;
ALTER TABLE scene_batches DROP COLUMN major_id;
ALTER TABLE lesson_batches DROP COLUMN major_id;
ALTER TABLE courses DROP COLUMN major_id;
ALTER TABLE position_recommendations DROP COLUMN major_id;
ALTER TABLE batches DROP COLUMN major_id;
