DROP TABLE IF EXISTS career_position_majors;

ALTER TABLE scenarios DROP CONSTRAINT fk_scenarios_industry;
ALTER TABLE scenarios DROP CONSTRAINT fk_scenarios_creator;
ALTER TABLE scenarios DROP CONSTRAINT fk_scenarios_tenant;
ALTER TABLE knowledge_points DROP CONSTRAINT fk_knowledge_points_creator;
ALTER TABLE knowledge_points DROP CONSTRAINT fk_knowledge_points_tenant;
ALTER TABLE question_banks DROP CONSTRAINT fk_question_banks_creator;
ALTER TABLE question_banks DROP CONSTRAINT fk_question_banks_tenant;
ALTER TABLE exams DROP CONSTRAINT fk_exams_creator;
ALTER TABLE exams DROP CONSTRAINT fk_exams_tenant;
ALTER TABLE exam_usages DROP CONSTRAINT fk_exam_usages_creator;
ALTER TABLE courses DROP CONSTRAINT fk_courses_creator;
ALTER TABLE courses DROP CONSTRAINT fk_courses_tenant;
ALTER TABLE career_positions DROP CONSTRAINT fk_career_positions_creator;
ALTER TABLE career_positions DROP CONSTRAINT fk_career_positions_tenant;
ALTER TABLE majors DROP CONSTRAINT fk_majors_tenant;
ALTER TABLE industries DROP CONSTRAINT fk_industries_tenant_fk;
ALTER TABLE questions DROP CONSTRAINT fk_questions_tenant;
ALTER TABLE ability_points DROP CONSTRAINT fk_ability_points_tenant;
