ALTER TABLE resources ADD COLUMN view_count INT NOT NULL DEFAULT 0;
ALTER TABLE scenarios ADD COLUMN view_count INT NOT NULL DEFAULT 0;
ALTER TABLE courses ADD COLUMN view_count INT NOT NULL DEFAULT 0;

DROP TABLE IF EXISTS view_logs;
