-- 回滚：将 users.tenant_id 改回 SET NULL，下游外键改回 SET NULL / NO ACTION

-- 1) 评估/业务表外键改回 NO ACTION（默认）
DO $$ BEGIN ALTER TABLE scene_evaluation_results       DROP CONSTRAINT IF EXISTS scene_evaluation_results_evaluatee_id_fkey;  ALTER TABLE scene_evaluation_results       ADD CONSTRAINT scene_evaluation_results_evaluatee_id_fkey  FOREIGN KEY (evaluatee_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE scene_evaluation_results       DROP CONSTRAINT IF EXISTS scene_evaluation_results_evaluator_id_fkey;  ALTER TABLE scene_evaluation_results       ADD CONSTRAINT scene_evaluation_results_evaluator_id_fkey  FOREIGN KEY (evaluator_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE scene_evaluation_results       DROP CONSTRAINT IF EXISTS scene_evaluation_results_graded_by_fkey;     ALTER TABLE scene_evaluation_results       ADD CONSTRAINT scene_evaluation_results_graded_by_fkey     FOREIGN KEY (graded_by)    REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE job_ability_results            DROP CONSTRAINT IF EXISTS job_ability_results_user_id_fkey;            ALTER TABLE job_ability_results            ADD CONSTRAINT job_ability_results_user_id_fkey            FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE student_ability_portraits      DROP CONSTRAINT IF EXISTS student_ability_portraits_user_id_fkey;      ALTER TABLE student_ability_portraits      ADD CONSTRAINT student_ability_portraits_user_id_fkey      FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE student_ability_archives       DROP CONSTRAINT IF EXISTS student_ability_archives_user_id_fkey;       ALTER TABLE student_ability_archives       ADD CONSTRAINT student_ability_archives_user_id_fkey       FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE graduation_project_archives    DROP CONSTRAINT IF EXISTS graduation_project_archives_user_id_fkey;    ALTER TABLE graduation_project_archives    ADD CONSTRAINT graduation_project_archives_user_id_fkey    FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE graduation_project_evaluations DROP CONSTRAINT IF EXISTS graduation_project_evaluations_user_id_fkey; ALTER TABLE graduation_project_evaluations ADD CONSTRAINT graduation_project_evaluations_user_id_fkey FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE graduation_query_results       DROP CONSTRAINT IF EXISTS graduation_query_results_user_id_fkey;       ALTER TABLE graduation_query_results       ADD CONSTRAINT graduation_query_results_user_id_fkey       FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE cert_issuance_records          DROP CONSTRAINT IF EXISTS cert_issuance_records_user_id_fkey;          ALTER TABLE cert_issuance_records          ADD CONSTRAINT cert_issuance_records_user_id_fkey          FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE appeal_records                 DROP CONSTRAINT IF EXISTS appeal_records_user_id_fkey;                 ALTER TABLE appeal_records                 ADD CONSTRAINT appeal_records_user_id_fkey                 FOREIGN KEY (user_id)     REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2) creator_id 外键改回 SET NULL
DO $$ BEGIN ALTER TABLE scenarios        DROP CONSTRAINT IF EXISTS fk_scenarios_creator;        ALTER TABLE scenarios        ADD CONSTRAINT fk_scenarios_creator         FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE knowledge_points DROP CONSTRAINT IF EXISTS fk_knowledge_points_creator; ALTER TABLE knowledge_points ADD CONSTRAINT fk_knowledge_points_creator  FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE question_banks   DROP CONSTRAINT IF EXISTS fk_question_banks_creator;   ALTER TABLE question_banks   ADD CONSTRAINT fk_question_banks_creator    FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE exams            DROP CONSTRAINT IF EXISTS fk_exams_creator;            ALTER TABLE exams            ADD CONSTRAINT fk_exams_creator             FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE exam_usages      DROP CONSTRAINT IF EXISTS fk_exam_usages_creator;      ALTER TABLE exam_usages      ADD CONSTRAINT fk_exam_usages_creator       FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE courses          DROP CONSTRAINT IF EXISTS fk_courses_creator;          ALTER TABLE courses          ADD CONSTRAINT fk_courses_creator           FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE career_positions DROP CONSTRAINT IF EXISTS fk_career_positions_creator; ALTER TABLE career_positions ADD CONSTRAINT fk_career_positions_creator  FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 3) users.tenant_id 改回 SET NULL
ALTER TABLE users DROP CONSTRAINT fk_users_tenant;
ALTER TABLE users ADD CONSTRAINT fk_users_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
