import type { Course } from "./types/lesson-source"

export interface ArchiveTreeNode {
  id: string
  label: string
  level: "college" | "major" | "grade"
  children?: ArchiveTreeNode[]
}

export interface ArchiveEntry {
  id: string
  course: Course
  college: string
  major: string
  grade: string
  archivedAt: string
  semester: string
  studentCount: number
}

export const archiveTree: ArchiveTreeNode[] = [
  {
    id: "college-1",
    label: "信息工程学院",
    level: "college",
    children: [
      {
        id: "major-1-1",
        label: "软件工程专业",
        level: "major",
        children: [
          { id: "grade-1-1-1", label: "2026级", level: "grade" },
          { id: "grade-1-1-2", label: "2025级", level: "grade" },
        ],
      },
      {
        id: "major-1-2",
        label: "计算机网络技术专业",
        level: "major",
        children: [
          { id: "grade-1-2-1", label: "2026级", level: "grade" },
        ],
      },
    ],
  },
  {
    id: "college-2",
    label: "人工智能学院",
    level: "college",
    children: [
      {
        id: "major-2-1",
        label: "人工智能专业",
        level: "major",
        children: [
          { id: "grade-2-1-1", label: "2026级", level: "grade" },
          { id: "grade-2-1-2", label: "2025级", level: "grade" },
        ],
      },
    ],
  },
]

export const archiveEntries: ArchiveEntry[] = [
  {
    id: "archive-1",
    course: {
      id: "hybrid-1-archive",
      code: "HYB-SE-2026-001",
      name: "Web前端开发混合课程",
      type: "hybrid",
      category: "专业核心课",
      major: "软件工程专业",
      teacher: "周老师",
      industry: "计算机行业",
      version: "v1.0",
      updateDate: "2026-06-20",
      nodeCount: 8,
      lessonCount: 16,
      resourceCount: 32,
      viewCount: 1200,
      studyCount: 8600,
      status: "published",
      coverColor: "from-purple-800 to-indigo-500",
      creator: "李主任课题组",
      createDate: "2025-10-20",
      coCreator: "阿里云大学",
      batchGroup: "2025年冬季集训",
      courseTag: "混合课程",
      onlineHours: 24,
      offlineHours: 24,
      onlineWeight: 40,
      offlineWeight: 60,
      semester: "2026-2027-1",
      className: "软件工程2026级1班",
    },
    college: "信息工程学院",
    major: "软件工程专业",
    grade: "2026级",
    archivedAt: "2026-09-15",
    semester: "2026-2027-1",
    studentCount: 45,
  },
  {
    id: "archive-2",
    course: {
      id: "hybrid-2-archive",
      code: "HYB-SE-2026-002",
      name: "软件测试技术混合课程",
      type: "hybrid",
      category: "专业核心课",
      major: "软件工程专业",
      teacher: "吴老师",
      industry: "软件测试工程师",
      version: "v1.0",
      updateDate: "2026-06-18",
      nodeCount: 6,
      lessonCount: 12,
      resourceCount: 28,
      viewCount: 980,
      studyCount: 6200,
      status: "published",
      coverColor: "from-indigo-800 to-blue-500",
      creator: "王老师工作室",
      createDate: "2025-12-15",
      coCreator: "华为ICT学院",
      batchGroup: "2026年暑期实训",
      courseTag: "混合课程",
      onlineHours: 16,
      offlineHours: 32,
      onlineWeight: 30,
      offlineWeight: 70,
      semester: "2026-2027-1",
      className: "软件工程2026级2班",
    },
    college: "信息工程学院",
    major: "软件工程专业",
    grade: "2026级",
    archivedAt: "2026-09-15",
    semester: "2026-2027-1",
    studentCount: 42,
  },
  {
    id: "archive-3",
    course: {
      id: "hybrid-6-archive",
      code: "HYB-UI-2026-006",
      name: "UI/UX设计混合课程",
      type: "hybrid",
      category: "专业拓展课",
      major: "软件工程专业",
      teacher: "林老师",
      industry: "计算机行业",
      version: "v1.0",
      updateDate: "2026-06-28",
      nodeCount: 8,
      lessonCount: 16,
      resourceCount: 24,
      viewCount: 550,
      studyCount: 3100,
      status: "published",
      coverColor: "from-pink-700 to-rose-500",
      creator: "张教授团队",
      createDate: "2025-12-15",
      coCreator: "阿里云大学",
      batchGroup: "2026年秋季课程",
      courseTag: "混合课程",
      onlineHours: 18,
      offlineHours: 30,
      onlineWeight: 35,
      offlineWeight: 65,
      semester: "2026-2027-1",
      className: "软件工程2026级3班",
    },
    college: "信息工程学院",
    major: "软件工程专业",
    grade: "2026级",
    archivedAt: "2026-09-15",
    semester: "2026-2027-1",
    studentCount: 38,
  },
  {
    id: "archive-4",
    course: {
      id: "hybrid-8-archive",
      code: "HYB-CS-2026-008",
      name: "云计算平台实践混合课程",
      type: "hybrid",
      category: "专业核心课",
      major: "软件工程专业",
      teacher: "周老师",
      industry: "计算机行业",
      version: "v1.0",
      updateDate: "2026-07-05",
      nodeCount: 9,
      lessonCount: 18,
      resourceCount: 28,
      viewCount: 420,
      studyCount: 2100,
      status: "published",
      coverColor: "from-sky-700 to-indigo-500",
      creator: "王老师工作室",
      createDate: "2026-02-20",
      coCreator: "腾讯云学堂",
      batchGroup: "2026年暑期实训",
      courseTag: "混合课程",
      onlineHours: 20,
      offlineHours: 28,
      onlineWeight: 35,
      offlineWeight: 65,
      semester: "2026-2027-1",
      className: "软件工程2026级4班",
    },
    college: "信息工程学院",
    major: "软件工程专业",
    grade: "2026级",
    archivedAt: "2026-09-15",
    semester: "2026-2027-1",
    studentCount: 36,
  },
  {
    id: "archive-5",
    course: {
      id: "hybrid-1-archive-se25",
      code: "HYB-SE-2025-001",
      name: "Web前端开发混合课程",
      type: "hybrid",
      category: "专业核心课",
      major: "软件工程专业",
      teacher: "周老师",
      industry: "计算机行业",
      version: "v0.9",
      updateDate: "2025-09-10",
      nodeCount: 7,
      lessonCount: 14,
      resourceCount: 28,
      viewCount: 980,
      studyCount: 7200,
      status: "published",
      coverColor: "from-purple-800 to-indigo-500",
      creator: "李主任课题组",
      createDate: "2024-10-20",
      coCreator: "阿里云大学",
      batchGroup: "2025年冬季集训",
      courseTag: "混合课程",
      onlineHours: 20,
      offlineHours: 28,
      onlineWeight: 40,
      offlineWeight: 60,
      semester: "2025-2026-1",
      className: "软件工程2025级1班",
    },
    college: "信息工程学院",
    major: "软件工程专业",
    grade: "2025级",
    archivedAt: "2025-09-12",
    semester: "2025-2026-1",
    studentCount: 48,
  },
  {
    id: "archive-6",
    course: {
      id: "hybrid-3-archive",
      code: "HYB-AI-2026-003",
      name: "机器学习混合课程",
      type: "hybrid",
      category: "专业核心课",
      major: "人工智能专业",
      teacher: "王老师",
      industry: "计算机行业",
      version: "v1.0",
      updateDate: "2026-06-15",
      nodeCount: 10,
      lessonCount: 20,
      resourceCount: 36,
      viewCount: 850,
      studyCount: 4800,
      status: "published",
      coverColor: "from-violet-800 to-purple-500",
      creator: "杭州知与未来科技有限公司",
      createDate: "2026-01-10",
      coCreator: "腾讯云学堂",
      batchGroup: "2026年春季课程",
      courseTag: "混合课程",
      onlineHours: 20,
      offlineHours: 28,
      onlineWeight: 35,
      offlineWeight: 65,
      semester: "2026-2027-1",
      className: "人工智能2026级1班",
    },
    college: "人工智能学院",
    major: "人工智能专业",
    grade: "2026级",
    archivedAt: "2026-09-16",
    semester: "2026-2027-1",
    studentCount: 40,
  },
  {
    id: "archive-7",
    course: {
      id: "hybrid-5-archive",
      code: "HYB-BI-2026-005",
      name: "大数据分析混合课程",
      type: "hybrid",
      category: "专业核心课",
      major: "人工智能专业",
      teacher: "陈老师",
      industry: "计算机行业",
      version: "v1.0",
      updateDate: "2026-06-25",
      nodeCount: 10,
      lessonCount: 20,
      resourceCount: 30,
      viewCount: 680,
      studyCount: 4200,
      status: "published",
      coverColor: "from-yellow-700 to-amber-500",
      creator: "杭州知与未来科技有限公司",
      createDate: "2025-10-20",
      coCreator: "知与未来",
      batchGroup: "2026年春季课程",
      courseTag: "混合课程",
      onlineHours: 22,
      offlineHours: 26,
      onlineWeight: 40,
      offlineWeight: 60,
      semester: "2026-2027-1",
      className: "人工智能2026级2班",
    },
    college: "人工智能学院",
    major: "人工智能专业",
    grade: "2026级",
    archivedAt: "2026-09-16",
    semester: "2026-2027-1",
    studentCount: 35,
  },
  {
    id: "archive-8",
    course: {
      id: "hybrid-3-archive-se25",
      code: "HYB-AI-2025-001",
      name: "机器学习混合课程",
      type: "hybrid",
      category: "专业核心课",
      major: "人工智能专业",
      teacher: "王老师",
      industry: "计算机行业",
      version: "v0.8",
      updateDate: "2025-09-08",
      nodeCount: 9,
      lessonCount: 18,
      resourceCount: 32,
      viewCount: 720,
      studyCount: 3800,
      status: "published",
      coverColor: "from-violet-800 to-purple-500",
      creator: "杭州知与未来科技有限公司",
      createDate: "2025-01-10",
      coCreator: "腾讯云学堂",
      batchGroup: "2025年春季课程",
      courseTag: "混合课程",
      onlineHours: 18,
      offlineHours: 30,
      onlineWeight: 35,
      offlineWeight: 65,
      semester: "2025-2026-1",
      className: "人工智能2025级1班",
    },
    college: "人工智能学院",
    major: "人工智能专业",
    grade: "2025级",
    archivedAt: "2025-09-10",
    semester: "2025-2026-1",
    studentCount: 42,
  },
  {
    id: "archive-9",
    course: {
      id: "hybrid-4-archive",
      code: "HYB-CN-2026-004",
      name: "网络安全攻防混合课程",
      type: "hybrid",
      category: "专业拓展课",
      major: "计算机网络技术专业",
      teacher: "李老师",
      industry: "电子信息",
      version: "v1.0",
      updateDate: "2026-06-10",
      nodeCount: 7,
      lessonCount: 14,
      resourceCount: 26,
      viewCount: 720,
      studyCount: 3500,
      status: "published",
      coverColor: "from-fuchsia-800 to-pink-500",
      creator: "张教授团队",
      createDate: "2026-02-20",
      coCreator: "百度AI教育",
      batchGroup: "2026年秋季课程",
      courseTag: "混合课程",
      onlineHours: 18,
      offlineHours: 30,
      onlineWeight: 35,
      offlineWeight: 65,
      semester: "2026-2027-1",
      className: "计算机网络技术2026级1班",
    },
    college: "信息工程学院",
    major: "计算机网络技术专业",
    grade: "2026级",
    archivedAt: "2026-09-14",
    semester: "2026-2027-1",
    studentCount: 32,
  },
  {
    id: "archive-10",
    course: {
      id: "hybrid-7-archive",
      code: "HYB-DB-2026-007",
      name: "数据库管理与优化混合课程",
      type: "hybrid",
      category: "专业基础课",
      major: "计算机网络技术专业",
      teacher: "杨老师",
      industry: "电子信息",
      version: "v1.0",
      updateDate: "2026-07-02",
      nodeCount: 6,
      lessonCount: 12,
      resourceCount: 20,
      viewCount: 480,
      studyCount: 2600,
      status: "published",
      coverColor: "from-slate-700 to-gray-500",
      creator: "李主任课题组",
      createDate: "2026-01-10",
      coCreator: "华为ICT学院",
      batchGroup: "2025年冬季集训",
      courseTag: "混合课程",
      onlineHours: 14,
      offlineHours: 34,
      onlineWeight: 30,
      offlineWeight: 70,
      semester: "2026-2027-1",
      className: "计算机网络技术2026级2班",
    },
    college: "信息工程学院",
    major: "计算机网络技术专业",
    grade: "2026级",
    archivedAt: "2026-09-14",
    semester: "2026-2027-1",
    studentCount: 30,
  },
]

export function filterArchiveEntries(
  college: string | null,
  major: string | null,
  grade: string | null,
  search: string,
) {
  return archiveEntries.filter((entry) => {
    if (college && entry.college !== college) return false
    if (major && entry.major !== major) return false
    if (grade && entry.grade !== grade) return false
    if (search.trim()) {
      const kw = search.trim().toLowerCase()
      return (
        entry.course.name.toLowerCase().includes(kw) ||
        entry.course.code.toLowerCase().includes(kw)
      )
    }
    return true
  })
}
