import type { Position } from '@/lib/types/job-source'

export const mockPositions: Position[] = [
  {
    id: 'position-1',
    batchId: 'batch-1',
    version: 'V1.2',
    status: 'published',
    name: 'Java 后端开发工程师',
    shortName: 'Java后端',
    industry: '互联网/IT',
    majors: ['软件工程', '计算机科学与技术'],
    positionType: 'enterprise',
    salaryRange: [12000, 25000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-1', name: '软考中级' }, { id: 'cert-2', name: 'Oracle Java认证' }],
    description: '负责公司核心业务系统的后端开发工作，参与系统架构设计和技术方案制定，保障系统高可用和高性能。',
    responsibilities: [
      { id: 'resp-1-1', name: '后端服务设计与开发', description: '负责核心业务服务的设计、开发、测试与上线' },
      { id: 'resp-1-2', name: '系统架构设计', description: '参与微服务架构设计，制定技术方案' },
      { id: 'resp-1-3', name: '数据库设计与优化', description: '负责数据模型设计、SQL优化及分库分表策略' },
      { id: 'resp-1-4', name: '技术文档编写', description: '编写接口文档、技术方案及单元测试' },
    ],
    requirements: [
      '本科及以上学历，计算机相关专业',
      '熟练掌握 Java 编程语言及 JVM 原理',
      '熟悉 Spring Boot、Spring Cloud、MyBatis 等框架',
      '了解 MySQL、Redis、Kafka、Elasticsearch 等中间件',
      '具备良好的沟通能力和团队协作精神',
    ],
    careerPath: "横向发展：全栈工程师、技术产品经理、技术顾问\n纵向晋升：高级开发工程师 → 技术专家 → 架构师 → 技术总监",
    abilityModel: {
      nodes: [
        { id: 'r1-1', type: 'responsibility', data: { label: '后端服务开发', description: '核心服务开发能力' }, position: { x: 50, y: 100 } },
        { id: 'r1-2', type: 'responsibility', data: { label: '系统架构设计', description: '架构设计能力' }, position: { x: 50, y: 250 } },
        { id: 'u1-1', type: 'unit', data: { label: 'Java后端开发', description: 'Java生态技术栈' }, position: { x: 300, y: 100 } },
        { id: 'u1-2', type: 'unit', data: { label: '分布式架构', description: '分布式系统设计' }, position: { x: 300, y: 250 } },
        { id: 'a1-1', type: 'ability', data: { label: 'Java编程', category: '专业技能' }, position: { x: 550, y: 50 } },
        { id: 'a1-2', type: 'ability', data: { label: '数据库设计', category: '专业技能' }, position: { x: 550, y: 150 } },
        { id: 'a1-3', type: 'ability', data: { label: '系统架构', category: '专业技能' }, position: { x: 550, y: 250 } },
        { id: 'a1-4', type: 'ability', data: { label: '问题解决', category: '通用能力' }, position: { x: 550, y: 350 } },
      ],
      edges: [
        { id: 'e1-1', source: 'r1-1', target: 'u1-1' },
        { id: 'e1-2', source: 'r1-2', target: 'u1-2' },
        { id: 'e1-3', source: 'u1-1', target: 'a1-1' },
        { id: 'e1-4', source: 'u1-1', target: 'a1-2' },
        { id: 'e1-5', source: 'u1-2', target: 'a1-3' },
        { id: 'e1-6', source: 'u1-2', target: 'a1-4' },
      ],
    },
    competencyConfig: [
      { id: 'cc-1-1', abilityId: 'ability-1', abilityName: 'Java 编程', level: 'proficient', ruleDescription: '能够独立完成复杂业务功能开发', weight: 30 },
      { id: 'cc-1-2', abilityId: 'ability-4', abilityName: '数据库设计', level: 'master', ruleDescription: '能够进行数据库表设计和SQL优化', weight: 25 },
      { id: 'cc-1-3', abilityId: 'ability-5', abilityName: '系统架构', level: 'comprehend', ruleDescription: '理解常见架构模式和设计原则', weight: 20 },
      { id: 'cc-1-4', abilityId: 'ability-7', abilityName: '问题解决', level: 'master', ruleDescription: '能够快速定位和解决技术问题', weight: 25 },
    ],
    abilityBindings: [
      { id: 'bind-1-1', responsibilityId: 'resp-1-1', source: 'public', publicAbilityId: 'ability-1', name: 'Java编程', category: '专业技能', level: 'proficient', rubricDescription: '熟练使用Java进行业务开发' },
      { id: 'bind-1-2', responsibilityId: 'resp-1-1', source: 'public', publicAbilityId: 'ability-12', name: 'Git版本控制', category: '工具应用', level: 'master', rubricDescription: '熟练使用Git进行团队协作' },
      { id: 'bind-1-3', responsibilityId: 'resp-1-2', source: 'public', publicAbilityId: 'ability-5', name: '系统架构', category: '专业技能', level: 'comprehend', rubricDescription: '理解微服务架构设计' },
      { id: 'bind-1-4', responsibilityId: 'resp-1-3', source: 'public', publicAbilityId: 'ability-4', name: '数据库设计', category: '专业技能', level: 'master', rubricDescription: '掌握MySQL设计与优化' },
      { id: 'bind-1-5', responsibilityId: 'resp-1-3', source: 'public', publicAbilityId: 'ability-14', name: 'Docker容器', category: '工具应用', level: 'understand', rubricDescription: '了解容器化部署' },
      { id: 'bind-1-6', responsibilityId: 'resp-1-4', source: 'public', publicAbilityId: 'ability-10', name: '沟通表达', category: '软技能', level: 'master', rubricDescription: '编写清晰技术文档' },
    ],
    abilityDomains: [
      { id: 'domain-1-1', name: '编程开发域', bindingIds: ['bind-1-1', 'bind-1-2'] },
      { id: 'domain-1-2', name: '架构设计域', bindingIds: ['bind-1-3'] },
      { id: 'domain-1-3', name: '数据管理域', bindingIds: ['bind-1-4', 'bind-1-5'] },
      { id: 'domain-1-4', name: '文档协作域', bindingIds: ['bind-1-6'] },
    ],
    createdBy: 'user-1',
    collaborators: ['user-1', 'user-2'],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
    favoriteCount: 128,
  },
  {
    id: 'position-2',
    batchId: 'batch-1',
    version: 'V1.0',
    status: 'published',
    name: '前端开发工程师',
    shortName: '前端开发',
    industry: '互联网/IT',
    majors: ['软件工程', '计算机科学与技术'],
    positionType: 'enterprise',
    salaryRange: [10000, 22000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-2-1', name: '前端高级工程师认证' }],
    description: '负责公司产品的前端开发工作，实现产品界面和交互功能，提升用户体验。',
    responsibilities: [
      { id: 'resp-2-1', name: '前端页面开发', description: '负责Web端和移动端页面开发' },
      { id: 'resp-2-2', name: '组件库建设', description: '开发和维护公共UI组件库' },
      { id: 'resp-2-3', name: '性能优化', description: '优化页面加载速度和渲染性能' },
      { id: 'resp-2-4', name: '交互设计实现', description: '与设计师协作实现交互动效' },
    ],
    requirements: [
      '本科及以上学历',
      '熟练掌握 HTML5/CSS3/JavaScript(ES6+)',
      '熟悉 React/Vue 框架及生态',
      '了解前端工程化、构建工具、性能优化',
      '有良好的审美和用户体验意识',
    ],
    careerPath: "横向发展：全栈工程师、UI设计师、产品经理\n纵向晋升：高级前端工程师 → 前端架构师 → 技术专家",
    abilityModel: {
      nodes: [
        { id: 'r2-1', type: 'responsibility', data: { label: '页面开发', description: '前端页面实现' }, position: { x: 50, y: 100 } },
        { id: 'u2-1', type: 'unit', data: { label: '前端开发能力', description: '核心前端技能' }, position: { x: 300, y: 100 } },
        { id: 'a2-1', type: 'ability', data: { label: '前端开发', category: '专业技能' }, position: { x: 550, y: 50 } },
        { id: 'a2-2', type: 'ability', data: { label: '沟通表达', category: '软技能' }, position: { x: 550, y: 150 } },
      ],
      edges: [
        { id: 'e2-1', source: 'r2-1', target: 'u2-1' },
        { id: 'e2-2', source: 'u2-1', target: 'a2-1' },
        { id: 'e2-3', source: 'u2-1', target: 'a2-2' },
      ],
    },
    competencyConfig: [
      { id: 'cc-2-1', abilityId: 'ability-3', abilityName: '前端开发', level: 'proficient', ruleDescription: '能够独立完成复杂前端功能开发', weight: 40 },
      { id: 'cc-2-2', abilityId: 'ability-10', abilityName: '沟通表达', level: 'master', ruleDescription: '能够清晰表达技术方案', weight: 20 },
    ],
    abilityBindings: [
      { id: 'bind-2-1', responsibilityId: 'resp-2-1', source: 'public', publicAbilityId: 'ability-3', name: '前端开发', category: '专业技能', level: 'proficient', rubricDescription: '熟练使用React/Vue开发' },
      { id: 'bind-2-2', responsibilityId: 'resp-2-1', source: 'public', publicAbilityId: 'ability-12', name: 'Git版本控制', category: '工具应用', level: 'master', rubricDescription: '熟练使用Git进行协作' },
      { id: 'bind-2-3', responsibilityId: 'resp-2-2', source: 'public', publicAbilityId: 'ability-3', name: '前端开发', category: '专业技能', level: 'proficient', rubricDescription: '组件化开发能力' },
      { id: 'bind-2-4', responsibilityId: 'resp-2-3', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'master', rubricDescription: '性能优化和问题排查' },
      { id: 'bind-2-5', responsibilityId: 'resp-2-4', source: 'public', publicAbilityId: 'ability-10', name: '沟通表达', category: '软技能', level: 'proficient', rubricDescription: '与设计师高效协作' },
    ],
    abilityDomains: [
      { id: 'domain-2-1', name: '前端技术域', bindingIds: ['bind-2-1', 'bind-2-2', 'bind-2-3'] },
      { id: 'domain-2-2', name: '性能优化域', bindingIds: ['bind-2-4'] },
      { id: 'domain-2-3', name: '协作设计域', bindingIds: ['bind-2-5'] },
    ],
    createdBy: 'user-1',
    collaborators: ['user-1'],
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-02-28T00:00:00Z',
    favoriteCount: 96,
  },
  {
    id: 'position-3',
    batchId: 'batch-2',
    version: 'V2.0',
    status: 'pending',
    name: '机器学习工程师',
    shortName: 'ML工程师',
    industry: '人工智能',
    majors: ['人工智能', '计算机科学与技术', '数学'],
    positionType: 'enterprise',
    salaryRange: [15000, 35000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-3-1', name: '机器学习认证' }, { id: 'cert-3-2', name: '深度学习认证' }],
    description: '负责公司AI产品的算法研发和模型训练工作，推动AI技术在业务中的应用落地。',
    responsibilities: [
      { id: 'resp-3-1', name: '算法研究与开发', description: '研究和实现机器学习算法' },
      { id: 'resp-3-2', name: '数据预处理与特征工程', description: '数据清洗、特征提取与选择' },
      { id: 'resp-3-3', name: '模型训练与优化', description: '训练深度学习模型并调优' },
      { id: 'resp-3-4', name: '模型部署与推理优化', description: '将模型部署到生产环境' },
    ],
    requirements: [
      '硕士及以上学历优先',
      '熟练掌握 Python 编程及NumPy/Pandas',
      '熟悉 TensorFlow/PyTorch 等深度学习框架',
      '有计算机视觉或NLP项目经验',
      '具备扎实的数学和统计学基础',
    ],
    careerPath: "横向发展：数据科学家、AI产品经理、技术顾问\n纵向晋升：高级算法工程师 → 算法专家 → 首席科学家",
    abilityModel: {
      nodes: [
        { id: 'r3-1', type: 'responsibility', data: { label: '算法研发', description: '算法研究和开发' }, position: { x: 50, y: 100 } },
        { id: 'u3-1', type: 'unit', data: { label: '机器学习能力', description: '核心ML技能' }, position: { x: 300, y: 100 } },
        { id: 'a3-1', type: 'ability', data: { label: 'Python编程', category: '专业技能' }, position: { x: 550, y: 50 } },
        { id: 'a3-2', type: 'ability', data: { label: '问题解决', category: '通用能力' }, position: { x: 550, y: 150 } },
      ],
      edges: [
        { id: 'e3-1', source: 'r3-1', target: 'u3-1' },
        { id: 'e3-2', source: 'u3-1', target: 'a3-1' },
        { id: 'e3-3', source: 'u3-1', target: 'a3-2' },
      ],
    },
    competencyConfig: [
      { id: 'cc-3-1', abilityId: 'ability-2', abilityName: 'Python 编程', level: 'proficient', ruleDescription: '能够熟练使用Python进行算法开发', weight: 35 },
      { id: 'cc-3-2', abilityId: 'ability-7', abilityName: '问题解决', level: 'proficient', ruleDescription: '能够独立解决复杂技术问题', weight: 30 },
    ],
    abilityBindings: [
      { id: 'bind-3-1', responsibilityId: 'resp-3-1', source: 'public', publicAbilityId: 'ability-2', name: 'Python编程', category: '专业技能', level: 'proficient', rubricDescription: '熟练使用Python进行算法开发' },
      { id: 'bind-3-2', responsibilityId: 'resp-3-1', source: 'public', publicAbilityId: 'ability-6', name: '需求分析', category: '通用能力', level: 'master', rubricDescription: '理解业务需求转化为算法问题' },
      { id: 'bind-3-3', responsibilityId: 'resp-3-2', source: 'public', publicAbilityId: 'ability-2', name: 'Python编程', category: '专业技能', level: 'proficient', rubricDescription: '数据处理和特征工程' },
      { id: 'bind-3-4', responsibilityId: 'resp-3-3', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'proficient', rubricDescription: '模型调优和问题排查' },
      { id: 'bind-3-5', responsibilityId: 'resp-3-4', source: 'public', publicAbilityId: 'ability-14', name: 'Docker容器', category: '工具应用', level: 'comprehend', rubricDescription: '模型容器化部署' },
    ],
    abilityDomains: [
      { id: 'domain-3-1', name: '算法研发域', bindingIds: ['bind-3-1', 'bind-3-2'] },
      { id: 'domain-3-2', name: '数据处理域', bindingIds: ['bind-3-3'] },
      { id: 'domain-3-3', name: '模型优化域', bindingIds: ['bind-3-4', 'bind-3-5'] },
    ],
    createdBy: 'user-1',
    collaborators: ['user-1', 'user-2', 'user-3'],
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
    favoriteCount: 75,
  },
  {
    id: 'position-4',
    batchId: 'batch-1',
    version: 'V1.0',
    status: 'draft',
    name: '测试开发工程师',
    shortName: '测试开发',
    industry: '互联网/IT',
    majors: ['软件工程', '计算机科学与技术'],
    positionType: 'enterprise',
    salaryRange: [10000, 20000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-4-1', name: 'ISTQB认证' }],
    description: '负责公司产品的质量保障工作，设计和执行测试用例，开发自动化测试工具。',
    responsibilities: [
      { id: 'resp-4-1', name: '测试用例设计与执行', description: '设计功能、接口、性能测试用例' },
      { id: 'resp-4-2', name: '自动化测试开发', description: '开发UI和接口自动化测试脚本' },
      { id: 'resp-4-3', name: '缺陷跟踪与管理', description: '跟踪缺陷生命周期，推动修复' },
      { id: 'resp-4-4', name: '质量体系建设', description: '参与制定测试流程和质量标准' },
    ],
    requirements: [
      '本科及以上学历',
      '熟悉软件测试理论和流程',
      '掌握至少一门编程语言（Python/Java）',
      '了解自动化测试框架（Selenium/Appium）',
      '有较强的逻辑思维和质量意识',
    ],
    careerPath: "横向发展：开发工程师、产品经理、项目经理\n纵向晋升：高级测试工程师 → 测试架构师 → 质量总监",
    abilityModel: {
      nodes: [],
      edges: [],
    },
    competencyConfig: [],
    abilityBindings: [
      { id: 'bind-4-1', responsibilityId: 'resp-4-1', source: 'public', publicAbilityId: 'ability-6', name: '需求分析', category: '通用能力', level: 'master', rubricDescription: '基于需求设计测试用例' },
      { id: 'bind-4-2', responsibilityId: 'resp-4-2', source: 'public', publicAbilityId: 'ability-2', name: 'Python编程', category: '专业技能', level: 'proficient', rubricDescription: '编写自动化测试脚本' },
      { id: 'bind-4-3', responsibilityId: 'resp-4-2', source: 'public', publicAbilityId: 'ability-12', name: 'Git版本控制', category: '工具应用', level: 'master', rubricDescription: '管理测试代码版本' },
      { id: 'bind-4-4', responsibilityId: 'resp-4-3', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'proficient', rubricDescription: '分析缺陷根因' },
      { id: 'bind-4-5', responsibilityId: 'resp-4-4', source: 'public', publicAbilityId: 'ability-8', name: '项目管理', category: '通用能力', level: 'understand', rubricDescription: '了解质量管理流程' },
    ],
    abilityDomains: [
      { id: 'domain-4-1', name: '测试设计域', bindingIds: ['bind-4-1'] },
      { id: 'domain-4-2', name: '自动化域', bindingIds: ['bind-4-2', 'bind-4-3'] },
      { id: 'domain-4-3', name: '质量管理域', bindingIds: ['bind-4-4', 'bind-4-5'] },
    ],
    createdBy: 'user-1',
    collaborators: ['user-1'],
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
    favoriteCount: 32,
  },
  {
    id: 'position-5',
    batchId: 'batch-3',
    version: 'V1.1',
    status: 'published',
    name: '市场营销专员',
    shortName: '营销专员',
    industry: '市场营销',
    majors: ['市场营销', '工商管理'],
    positionType: 'enterprise',
    salaryRange: [8000, 15000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-5-1', name: '数字营销师证书' }],
    description: '负责公司产品的市场推广和品牌建设工作，制定营销策略，执行营销活动。',
    responsibilities: [
      { id: 'resp-5-1', name: '市场调研与分析', description: '收集市场信息，分析竞品和用户需求' },
      { id: 'resp-5-2', name: '营销活动策划执行', description: '策划线上线下营销活动并落地执行' },
      { id: 'resp-5-3', name: '内容运营与传播', description: '管理社交媒体，产出传播内容' },
      { id: 'resp-5-4', name: '数据分析与复盘', description: '分析营销数据，输出复盘报告' },
    ],
    requirements: [
      '本科及以上学历，市场营销相关专业',
      '有较强的文案写作和创意策划能力',
      '熟悉各类数字营销渠道和工具',
      '有数据敏感度和分析能力',
      '良好的沟通协调和跨部门协作能力',
    ],
    careerPath: "横向发展：品牌经理、产品经理、商务拓展\n纵向晋升：高级营销专员 → 营销经理 → 市场总监",
    abilityModel: {
      nodes: [
        { id: 'r5-1', type: 'responsibility', data: { label: '营销策划', description: '营销活动策划' }, position: { x: 50, y: 100 } },
        { id: 'u5-1', type: 'unit', data: { label: '营销能力', description: '核心营销技能' }, position: { x: 300, y: 100 } },
        { id: 'a5-1', type: 'ability', data: { label: '沟通表达', category: '软技能' }, position: { x: 550, y: 100 } },
      ],
      edges: [
        { id: 'e5-1', source: 'r5-1', target: 'u5-1' },
        { id: 'e5-2', source: 'u5-1', target: 'a5-1' },
      ],
    },
    competencyConfig: [
      { id: 'cc-5-1', abilityId: 'ability-10', abilityName: '沟通表达', level: 'proficient', ruleDescription: '能够清晰表达营销方案', weight: 40 },
    ],
    abilityBindings: [
      { id: 'bind-5-1', responsibilityId: 'resp-5-1', source: 'public', publicAbilityId: 'ability-6', name: '需求分析', category: '通用能力', level: 'proficient', rubricDescription: '市场分析和用户调研' },
      { id: 'bind-5-2', responsibilityId: 'resp-5-2', source: 'public', publicAbilityId: 'ability-10', name: '沟通表达', category: '软技能', level: 'proficient', rubricDescription: '营销策划和沟通' },
      { id: 'bind-5-3', responsibilityId: 'resp-5-3', source: 'public', publicAbilityId: 'ability-11', name: '学习能力', category: '软技能', level: 'master', rubricDescription: '快速学习新媒体玩法' },
      { id: 'bind-5-4', responsibilityId: 'resp-5-4', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'comprehend', rubricDescription: '数据分析和策略调整' },
    ],
    abilityDomains: [
      { id: 'domain-5-1', name: '市场分析域', bindingIds: ['bind-5-1'] },
      { id: 'domain-5-2', name: '营销策划域', bindingIds: ['bind-5-2', 'bind-5-3'] },
      { id: 'domain-5-3', name: '数据复盘域', bindingIds: ['bind-5-4'] },
    ],
    createdBy: 'user-2',
    collaborators: ['user-2', 'user-1'],
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
    favoriteCount: 45,
  },
  {
    id: 'position-6',
    batchId: 'batch-1',
    version: 'V1.0',
    status: 'rejected',
    name: '运维工程师',
    shortName: '运维',
    industry: '互联网/IT',
    majors: ['软件工程', '计算机科学与技术'],
    positionType: 'enterprise',
    salaryRange: [10000, 20000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-6-1', name: 'CKA认证' }, { id: 'cert-6-2', name: 'AWS认证' }],
    description: '负责公司服务器和网络设备的运维工作，保障系统稳定运行，推动运维自动化。',
    responsibilities: [
      { id: 'resp-6-1', name: '服务器运维监控', description: '服务器日常运维和监控告警' },
      { id: 'resp-6-2', name: '故障排查与恢复', description: '处理系统故障和应急恢复' },
      { id: 'resp-6-3', name: 'CI/CD流水线建设', description: '构建持续集成部署流水线' },
      { id: 'resp-6-4', name: '运维自动化开发', description: '开发运维脚本和自动化工具' },
    ],
    requirements: [
      '本科及以上学历',
      '熟悉 Linux 操作系统及内核调优',
      '了解网络协议和安全防护',
      '掌握 Shell/Python 脚本编写',
      '熟悉 Kubernetes/Docker 容器技术',
    ],
    careerPath: "横向发展：开发工程师、安全工程师、云架构师\n纵向晋升：高级运维工程师 → 运维架构师 → 运维总监",
    abilityModel: {
      nodes: [],
      edges: [],
    },
    competencyConfig: [],
    abilityBindings: [
      { id: 'bind-6-1', responsibilityId: 'resp-6-1', source: 'public', publicAbilityId: 'ability-13', name: 'Linux系统', category: '工具应用', level: 'proficient', rubricDescription: '熟练运维Linux服务器' },
      { id: 'bind-6-2', responsibilityId: 'resp-6-1', source: 'public', publicAbilityId: 'ability-14', name: 'Docker容器', category: '工具应用', level: 'master', rubricDescription: '容器化部署和管理' },
      { id: 'bind-6-3', responsibilityId: 'resp-6-2', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'proficient', rubricDescription: '快速排查和恢复故障' },
      { id: 'bind-6-4', responsibilityId: 'resp-6-3', source: 'public', publicAbilityId: 'ability-12', name: 'Git版本控制', category: '工具应用', level: 'master', rubricDescription: '管理代码版本和发布' },
      { id: 'bind-6-5', responsibilityId: 'resp-6-4', source: 'public', publicAbilityId: 'ability-2', name: 'Python编程', category: '专业技能', level: 'comprehend', rubricDescription: '编写运维自动化脚本' },
    ],
    abilityDomains: [
      { id: 'domain-6-1', name: '系统运维域', bindingIds: ['bind-6-1', 'bind-6-2'] },
      { id: 'domain-6-2', name: '故障处理域', bindingIds: ['bind-6-3'] },
      { id: 'domain-6-3', name: '自动化域', bindingIds: ['bind-6-4', 'bind-6-5'] },
    ],
    createdBy: 'user-2',
    collaborators: ['user-2'],
    createdAt: '2024-02-25T00:00:00Z',
    updatedAt: '2024-03-08T00:00:00Z',
    favoriteCount: 18,
  },
  {
    id: 'position-7',
    batchId: 'batch-2',
    version: 'V1.0',
    status: 'approved',
    name: '产品经理',
    shortName: 'PM',
    industry: '互联网/IT',
    majors: ['产品设计', '工商管理', '计算机科学'],
    positionType: 'enterprise',
    salaryRange: [15000, 30000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-7-1', name: 'NPDP认证' }],
    description: '负责产品规划和需求管理，推动产品从概念到上线的全过程，持续提升产品价值。',
    responsibilities: [
      { id: 'resp-7-1', name: '产品需求分析', description: '收集和分析用户需求，编写PRD' },
      { id: 'resp-7-2', name: '产品原型设计', description: '设计产品原型和交互流程' },
      { id: 'resp-7-3', name: '项目进度管理', description: '协调研发资源，跟踪项目进度' },
      { id: 'resp-7-4', name: '数据驱动决策', description: '分析产品数据，驱动产品迭代' },
    ],
    requirements: [
      '本科及以上学历',
      '有3年以上互联网产品经验',
      '熟练使用Axure/Figma等原型工具',
      '具备优秀的逻辑思维和数据分析能力',
      '有较强的沟通协调和跨团队协作能力',
    ],
    careerPath: "横向发展：运营总监、业务负责人、创业者\n纵向晋升：高级产品经理 → 产品总监 → VP产品",
    abilityModel: {
      nodes: [],
      edges: [],
    },
    competencyConfig: [],
    abilityBindings: [
      { id: 'bind-7-1', responsibilityId: 'resp-7-1', source: 'public', publicAbilityId: 'ability-6', name: '需求分析', category: '通用能力', level: 'proficient', rubricDescription: '深度理解用户需求' },
      { id: 'bind-7-2', responsibilityId: 'resp-7-2', source: 'public', publicAbilityId: 'ability-10', name: '沟通表达', category: '软技能', level: 'proficient', rubricDescription: '清晰表达产品方案' },
      { id: 'bind-7-3', responsibilityId: 'resp-7-3', source: 'public', publicAbilityId: 'ability-8', name: '项目管理', category: '通用能力', level: 'master', rubricDescription: '高效管理项目进度' },
      { id: 'bind-7-4', responsibilityId: 'resp-7-4', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'proficient', rubricDescription: '数据分析和决策能力' },
    ],
    abilityDomains: [
      { id: 'domain-7-1', name: '需求分析域', bindingIds: ['bind-7-1'] },
      { id: 'domain-7-2', name: '产品设计域', bindingIds: ['bind-7-2'] },
      { id: 'domain-7-3', name: '项目管理域', bindingIds: ['bind-7-3', 'bind-7-4'] },
    ],
    createdBy: 'user-1',
    collaborators: ['user-1', 'user-2'],
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
    favoriteCount: 62,
  },
  {
    id: 'position-8',
    batchId: 'batch-3',
    version: 'V1.0',
    status: 'draft',
    name: 'UI设计师',
    shortName: 'UI设计',
    industry: '互联网/IT',
    majors: ['视觉传达', '数字媒体艺术'],
    positionType: 'enterprise',
    salaryRange: [9000, 18000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-8-1', name: 'Adobe认证设计师' }],
    description: '负责产品界面的视觉设计和交互优化，确保产品拥有优秀的用户体验。',
    responsibilities: [
      { id: 'resp-8-1', name: '界面视觉设计', description: '设计产品界面和视觉规范' },
      { id: 'resp-8-2', name: '交互原型设计', description: '设计交互流程和动效' },
      { id: 'resp-8-3', name: '设计规范维护', description: '维护设计系统和组件库' },
      { id: 'resp-8-4', name: '用户体验优化', description: '基于反馈持续优化设计' },
    ],
    requirements: [
      '本科及以上学历，设计相关专业',
      '熟练使用Figma/Sketch/PS等设计工具',
      '有良好的审美和创意能力',
      '了解前端开发基础，能与开发协作',
      '注重细节，追求极致的用户体验',
    ],
    careerPath: "横向发展：产品经理、创意总监、品牌顾问\n纵向晋升：高级UI设计师 → 设计总监 → 创意VP",
    abilityModel: {
      nodes: [],
      edges: [],
    },
    competencyConfig: [],
    abilityBindings: [
      { id: 'bind-8-1', responsibilityId: 'resp-8-1', source: 'public', publicAbilityId: 'ability-10', name: '沟通表达', category: '软技能', level: 'proficient', rubricDescription: '视觉表达和沟通' },
      { id: 'bind-8-2', responsibilityId: 'resp-8-2', source: 'public', publicAbilityId: 'ability-6', name: '需求分析', category: '通用能力', level: 'comprehend', rubricDescription: '理解用户交互需求' },
      { id: 'bind-8-3', responsibilityId: 'resp-8-3', source: 'public', publicAbilityId: 'ability-11', name: '学习能力', category: '软技能', level: 'master', rubricDescription: '跟进设计趋势' },
      { id: 'bind-8-4', responsibilityId: 'resp-8-4', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'comprehend', rubricDescription: '基于数据优化设计' },
    ],
    abilityDomains: [
      { id: 'domain-8-1', name: '视觉设计域', bindingIds: ['bind-8-1'] },
      { id: 'domain-8-2', name: '交互设计域', bindingIds: ['bind-8-2'] },
      { id: 'domain-8-3', name: '规范优化域', bindingIds: ['bind-8-3', 'bind-8-4'] },
    ],
    createdBy: 'user-2',
    collaborators: ['user-2', 'user-1'],
    createdAt: '2024-03-05T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
    favoriteCount: 54,
  },
  {
    id: 'position-9',
    batchId: 'batch-1',
    version: 'V1.0',
    status: 'published',
    name: '软件工程教学实践岗',
    shortName: '软工教学岗',
    industry: '教育',
    majors: ['软件工程', '计算机科学与技术'],
    positionType: 'teaching',
    salaryRange: [5000, 8000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-9-1', name: '教师资格证' }],
    description: '面向软件工程专业学生的教学实践岗位，指导学生完成课程项目、实训场景与企业真实项目对接。',
    responsibilities: [
      { id: 'resp-9-1', name: '课程项目指导', description: '指导学生完成软件工程课程项目' },
      { id: 'resp-9-2', name: '实训场景设计', description: '设计贴近企业的实训任务与场景' },
      { id: 'resp-9-3', name: '企业项目对接', description: '将企业真实需求转化为教学案例' },
    ],
    requirements: [
      '硕士及以上学历，软件工程或相关专业',
      '具备企业软件开发经验',
      '热爱教学，具备良好的沟通能力',
    ],
    careerPath: "横向发展：企业工程师、技术培训师\n纵向晋升：讲师 → 高级讲师 → 副教授 → 教授",
    abilityModel: {
      nodes: [],
      edges: [],
    },
    competencyConfig: [],
    abilityBindings: [
      { id: 'bind-9-1', responsibilityId: 'resp-9-1', source: 'public', publicAbilityId: 'ability-1', name: 'Java编程', category: '专业技能', level: 'proficient', rubricDescription: '指导学生Java项目开发' },
      { id: 'bind-9-2', responsibilityId: 'resp-9-2', source: 'public', publicAbilityId: 'ability-10', name: '沟通表达', category: '软技能', level: 'proficient', rubricDescription: '清晰传达实训要求' },
      { id: 'bind-9-3', responsibilityId: 'resp-9-3', source: 'public', publicAbilityId: 'ability-6', name: '需求分析', category: '通用能力', level: 'master', rubricDescription: '将企业需求转化为教学案例' },
    ],
    abilityDomains: [
      { id: 'domain-9-1', name: '项目指导域', bindingIds: ['bind-9-1'] },
      { id: 'domain-9-2', name: '教学沟通域', bindingIds: ['bind-9-2', 'bind-9-3'] },
    ],
    createdBy: 'user-1',
    collaborators: ['user-1'],
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
    favoriteCount: 22,
  },
  {
    id: 'position-10',
    batchId: 'batch-2',
    version: 'V1.0',
    status: 'published',
    name: '人工智能教学实践岗',
    shortName: 'AI教学岗',
    industry: '教育',
    majors: ['人工智能', '计算机科学与技术'],
    positionType: 'teaching',
    salaryRange: [6000, 10000],
    coverImage: '/placeholder.svg?height=200&width=300',
    certificates: [{ id: 'cert-10-1', name: '教师资格证' }, { id: 'cert-10-2', name: '深度学习工程师认证' }],
    description: '面向人工智能专业学生的教学实践岗位，负责算法实验课程、竞赛指导与科研入门训练。',
    responsibilities: [
      { id: 'resp-10-1', name: '算法实验教学', description: '指导学生完成机器学习与深度学习实验' },
      { id: 'resp-10-2', name: '学科竞赛指导', description: '组织学生参加AI相关学科竞赛' },
      { id: 'resp-10-3', name: '科研入门训练', description: '引导学生进入科研课题与论文阅读' },
    ],
    requirements: [
      '硕士及以上学历，人工智能或计算机相关专业',
      '有深度学习项目或科研经验',
      '具备指导学生竞赛和科研的能力',
    ],
    careerPath: "横向发展：企业算法工程师、AI产品经理\n纵向晋升：讲师 → 高级讲师 → 副教授 → 教授",
    abilityModel: {
      nodes: [],
      edges: [],
    },
    competencyConfig: [],
    abilityBindings: [
      { id: 'bind-10-1', responsibilityId: 'resp-10-1', source: 'public', publicAbilityId: 'ability-2', name: 'Python编程', category: '专业技能', level: 'proficient', rubricDescription: '指导学生Python算法实验' },
      { id: 'bind-10-2', responsibilityId: 'resp-10-2', source: 'public', publicAbilityId: 'ability-7', name: '问题解决', category: '通用能力', level: 'proficient', rubricDescription: '竞赛问题分析与方案设计' },
      { id: 'bind-10-3', responsibilityId: 'resp-10-3', source: 'public', publicAbilityId: 'ability-11', name: '学习能力', category: '软技能', level: 'master', rubricDescription: '跟踪前沿论文与技术' },
    ],
    abilityDomains: [
      { id: 'domain-10-1', name: '实验教学域', bindingIds: ['bind-10-1'] },
      { id: 'domain-10-2', name: '竞赛科研域', bindingIds: ['bind-10-2', 'bind-10-3'] },
    ],
    createdBy: 'user-2',
    collaborators: ['user-2'],
    createdAt: '2024-03-12T00:00:00Z',
    updatedAt: '2024-03-12T00:00:00Z',
    favoriteCount: 18,
  },
]

export const getPositionById = (id: string): Position | undefined => {
  return mockPositions.find(position => position.id === id)
}

export const getPositionsByBatchId = (batchId: string): Position[] => {
  return mockPositions.filter(position => position.batchId === batchId)
}

export const getPositionsByStatus = (status: Position['status']): Position[] => {
  return mockPositions.filter(position => position.status === status)
}

export const getPublishedPositions = (): Position[] => {
  return mockPositions.filter(position => position.status === 'published')
}
